name: seqdahla
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.7.1
  - pip=22.3.1
  - pip:
    - allennlp==0.9.0
    - overrides==3.1.0
    - chardet
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy
  - pandas
  - seaborn
  - matplotlib
